# Generated by Django 4.1 on 2022-08-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('type', models.CharField(max_length=255, verbose_name='Тип товара')),
                ('date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('file', models.FileField(blank=True, upload_to='goods_delivery/files')),
            ],
        ),
        migrations.CreateModel(
            name='AddressIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Пункт выдачи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_delivery.product')),
            ],
        ),
    ]
